name: Sync All Branches to ADF-CICD-Loadtest-2

on:
  push:
    branches:
      - '**'  # Trigger on all branches

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for all branches
          ref: ${{ github.ref }}

      - name: Configure Git identity
        run: |
          git config --global user.email "mudulisitesh@gmail.com"
          git config --global user.name "Sitesh Muduli"

      - name: Add remote for destination repo
        run: |
          git remote add dest https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/mudulisitesh/ADF-CICD-Loadtest-2.git

      - name: Push current branch to destination
        run: |
          git push dest ${{ github.ref_name }} --force
