name: Mirror All Branches to Destination Repo

on:
  push:
    branches:
      - '**'  # Trigger on pushes to any branch

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important to get full history

      - name: Set Git identity
        run: |
          git config --global user.name "Sitesh Muduli"
          git config --global user.email "mudulisitesh@gmail.com"

      - name: Add destination repo as remote and push all branches
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Add destination repo with token-based authentication
          git remote add dest https://x-access-token:${TOKEN}@github.com/mudulisitesh/ADF-CICD-Loadtest-2.git
          
          # Push all branches and tags
          git push dest --all --force
          git push dest --tags --force
