name: Force Push Current Branch to ADF-CICD-Loadtest-2

on:
  push:
    branches:
      - '**'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Setup Git
        run: |
          git config --global user.name "Sitesh Muduli"
          git config --global user.email "mudulisitesh@gmail.com"

      - name: Push to destination repo
        run: |
          git remote add dest https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/mudulisitesh/ADF-CICD-Loadtest-2.git
          git push dest ${{ github.ref_name }} --force
